apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enemy-losses
  namespace: app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - demo.example.com
      secretName: enemy-losses-tls
  rules:
    - host: demo.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: enemy-losses-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enemy-losses-frontend
                port:
                  number: 80
