apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: war-climate-analytics-api
  namespace: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: war-climate-analytics-api

