apiVersion: v1
kind: Secret
metadata:
  name: war-climate-analytics-secrets
  namespace: app
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://pgadmin:replace-me@war-climate-analytics.postgres.database.azure.com:5432/war_climate_analytics
  ADMIN_API_KEY: replace-me

