apiVersion: v1
kind: Secret
metadata:
  name: enemy-losses-secrets
  namespace: app
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://pgadmin:replace-me@enemy-losses-weather.postgres.database.azure.com:5432/enemy_losses_weather
  ADMIN_API_KEY: replace-me

