apiVersion: v1
kind: Service
metadata:
  name: war-climate-analytics-api
  namespace: app
  labels:
    app: war-climate-analytics-api
spec:
  selector:
    app: war-climate-analytics-api
  ports:
    - name: http
      port: 80
      targetPort: 8000

