apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enemy-losses-api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: enemy-losses-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

