apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Yojimbos/WarClimate-Analytics
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/overlays/dev
  prune: true
  wait: true
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: issuer
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/issuers/dev
  prune: true
  wait: true
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
